apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ml-stack

resources:
  - namespace.yaml
  - sealed-secrets.yaml
  - configmaps.yaml
  - pvcs.yaml
  - postgres.yaml
  - rollout-guard.yaml

images:
  - name: ghcr.io/andrius-eng/ml-airflow-custom
    newTag: a358bfe8b8ae0eed65446b0848d0d13e64873112
  - name: ghcr.io/andrius-eng/ml-ml-pipeline
    newTag: a358bfe8b8ae0eed65446b0848d0d13e64873112
  - name: ghcr.io/andrius-eng/ml-frontend
    newTag: a358bfe8b8ae0eed65446b0848d0d13e64873112
  - name: ghcr.io/andrius-eng/ml-ws-server
    newTag: a358bfe8b8ae0eed65446b0848d0d13e64873112
