apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ml-stack

resources:
  - mlflow.yaml
  - dashboard.yaml

images:
  - name: ghcr.io/andrius-eng/ml-ml-pipeline
    newTag: ae6f77a8c2a2f796ffc2e8fed7e9c885ccd4b33d
  - name: ghcr.io/andrius-eng/ml-frontend
    newTag: ae6f77a8c2a2f796ffc2e8fed7e9c885ccd4b33d
  - name: ghcr.io/andrius-eng/ml-ws-server
    newTag: ae6f77a8c2a2f796ffc2e8fed7e9c885ccd4b33d
