apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ml-stack

resources:
  - mlflow.yaml
  - dashboard.yaml

images:
  - name: ghcr.io/andrius-eng/ml-ml-pipeline
    newTag: 31665de50beb6f1e08e84a0b07e1b0b456f5d8a1
  - name: ghcr.io/andrius-eng/ml-frontend
    newTag: 31665de50beb6f1e08e84a0b07e1b0b456f5d8a1
  - name: ghcr.io/andrius-eng/ml-ws-server
    newTag: 31665de50beb6f1e08e84a0b07e1b0b456f5d8a1
