apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ml-stack

resources:
  - mlflow.yaml
  - dashboard.yaml

images:
  - name: ghcr.io/andrius-eng/ml-ml-pipeline
    newTag: a28a1fbaf79f7797597204b8c45effcd88c178f3
  - name: ghcr.io/andrius-eng/ml-frontend
    newTag: a28a1fbaf79f7797597204b8c45effcd88c178f3
  - name: ghcr.io/andrius-eng/ml-ws-server
    newTag: a28a1fbaf79f7797597204b8c45effcd88c178f3
