apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ml-stack
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/andrius-eng/ml.git
    targetRevision: main
    path: kubernetes
    kustomize: {}
  destination:
    server: https://kubernetes.default.svc
    namespace: ml-stack
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
