apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ml-stack
resources:
  - ../../base
patchesStrategicMerge:
  - pvc-patch.yaml
  - image-override.yaml
  - pull-secret-patch.yaml
