apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-airflow-data
spec:
  capacity:
    storage: 5Gi
  accessModes: [ReadWriteMany]
  persistentVolumeReclaimPolicy: Retain
  storageClassName: k3s-hostpath
  hostPath:
    path: /tmp/k8s/pv-airflow-data
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-ml-output
spec:
  capacity:
    storage: 10Gi
  accessModes: [ReadWriteMany]
  persistentVolumeReclaimPolicy: Retain
  storageClassName: k3s-hostpath
  hostPath:
    path: /tmp/k8s/pv-ml-output
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-dashboard-data
spec:
  capacity:
    storage: 512Mi
  accessModes: [ReadWriteMany]
  persistentVolumeReclaimPolicy: Retain
  storageClassName: k3s-hostpath
  hostPath:
    path: /tmp/k8s/pv-dashboard-data
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-beam-artifacts
spec:
  capacity:
    storage: 2Gi
  accessModes: [ReadWriteMany]
  persistentVolumeReclaimPolicy: Retain
  storageClassName: k3s-hostpath
  hostPath:
    path: /tmp/k8s/pv-beam-artifacts
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-flink-job-archives
spec:
  capacity:
    storage: 2Gi
  accessModes: [ReadWriteMany]
  persistentVolumeReclaimPolicy: Retain
  storageClassName: k3s-hostpath
  hostPath:
    path: /tmp/k8s/pv-flink-job-archives
    type: DirectoryOrCreate
