apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ml-stack

resources:
  - ../../base

patches:
  - path: pvc-patch.yaml
    target:
      kind: PersistentVolumeClaim

# Pin image tags for production
# images:
#   - name: ghcr.io/andrius-eng/ml-airflow-custom
#     newTag: "sha-<commit>"
#   - name: ghcr.io/andrius-eng/ml-ml-pipeline
#     newTag: "sha-<commit>"
